handle bsd lib test

diff --git a/libft/Makefile b/libft/Makefile
--- a/libft/Makefile
+++ b/libft/Makefile
@@ -6,13 +6,13 @@
 #    By: jhoban <jhoban@student.42berlin.de>        +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2025/11/17 21:17:16 by jhoban            #+#    #+#              #
-#    Updated: 2025/11/20 12:17:35 by jhoban           ###   ########.fr        #
+#    Updated: 2025/11/20 12:20:12 by jhoban           ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
 NAME = libft.a
 
-.PHONY: all clean fclean ar test
+.PHONY: all clean fclean ar test test-mac
 all:
 	cc -Wall -Wextra -Werror -c *.c
 
@@ -26,8 +26,14 @@ fclean: clean
 ar: all
 	ar rcs $(NAME) *.o
 
-test: all ar
+test-mac: all ar
 	cc -o test ../test.c $(NAME)
+	echo "Running tests:"
+	./test | tee test_output.txt
+	grep "KO!" test_output.txt && echo "Some tests failed." || echo "All tests passed."
+
+test: all ar
+	cc -o test ../test.c $(NAME) -lbsd
 	echo "Running tests:"
 	./test | tee test_output.txt
 	grep "KO!" test_output.txt && echo "Some tests failed." || echo "All tests passed."
